### ISSUE TITLE
Please correct Build & Install instructions

### ISSUE THREAD

**Issue by dancbeaulieu** [pyscf/gpu4pyscf#10]
The command "python setup install" doesn't work after the "cd gpu4pyscf" command. Even using "python setup.py install" fails. Can you please help us figure out what correct way to fix these build & install issues are?

Error:
  (anh) dabeaulieu@USARRDABEAULIEUUB1:/home/shared/gpu4pyscf$ python setup.py install
  Warning: 'classifiers' should be a list, got type 'NoneType'
  Traceback (most recent call last):
    File "/home/shared/gpu4pyscf/setup.py", line 91, in <module>
      setup(
    File "/home/shared/anaconda3/envs/anh/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
      return distutils.core.setup(**attrs)
    File "/home/shared/anaconda3/envs/anh/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/shared/anaconda3/envs/anh/lib/python3.9/site-packages/setuptools/dist.py", line 488, in __init__
      _Distribution.__init__(
    File "/home/shared/anaconda3/envs/anh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 258, in __init__
      getattr(self.metadata, "set_" + key)(val)
    File "/home/shared/anaconda3/envs/anh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1242, in set_classifiers
      self.classifiers = _ensure_list(value, 'classifiers')
    File "/home/shared/anaconda3/envs/anh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 49, in _ensure_list
      value = list(value)
  TypeError: 'NoneType' object is not iterable

Python/Environment/Package information:
/home/shared/gpu4pyscf$python --version 
    Python 3.9.16
/home/shared/gpu4pyscf$ pip freeze
  alembic==1.9.4
  cmaes==0.9.1
  colorlog==6.7.0
  cupy @ file:///opt/conda/conda-bld/cupy_1610065936122/work
  fastrlock==0.6
  greenlet==2.0.2
  h5py==3.8.0
  Mako==1.2.4
  MarkupSafe==2.1.2
  mkl-fft==1.3.1
  mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186066731/work
  mkl-service==2.4.0
  numpy @ file:///croot/numpy_and_numpy_base_1672336185480/work
  optuna==3.1.0
  packaging==23.0
  pyscf==2.1.1
  PyYAML==6.0
  scipy==1.10.0
  six @ file:///tmp/build/80754af9/six_1644875935023/work
  SQLAlchemy==2.0.3
  tqdm==4.64.1
  typing_extensions==4.5.0

**Comment by MarcoBarroca** [comment]
Having the same issue as well. Seems like the issue might be with setuptools. Maybe downgrading it to an older version might solve it.

**Comment by Yasir-Ghunaim** [comment]
This may not be a proper solution but I tried to change the following parameters in `setup.py` from None:
```
CLASSIFIERS     = None
PLATFORMS       = None
```
To an empty list:
```
CLASSIFIERS     = []
PLATFORMS       = []
```

When running `python setup.py install`, the installation proceeds beyond the classifier error but it throws another error `error: command 'cmake' failed: Permission denied` which doesn't seem to be related this one.

**Comment by Obs01ete** [comment]
Hey @Yasir-Ghunaim how are you :) You almost made it. There is some missing dependency in CmakeLists which can be fixed by a single threaded build (j1). With the following patch it gets installed and runs well on V100.

```python
diff --git a/setup.py b/setup.py
index ff65aa3..b1ed366 100755
--- a/setup.py
+++ b/setup.py
@@ -28,8 +28,8 @@ DESCRIPTION     = 'GPU extensions for PySCF'
 LICENSE         = 'GPLv3'
 URL             = None
 DOWNLOAD_URL    = None
-CLASSIFIERS     = None
-PLATFORMS       = None
+CLASSIFIERS     = []
+PLATFORMS       = []
 
 def get_version():
     topdir = os.path.abspath(os.path.join(__file__, '..'))
@@ -61,7 +61,7 @@ class CMakeBuildExt(build_ext):
         self.spawn(cmd)
 
         self.announce('Building binaries', level=3)
-        cmd = ['cmake', '--build', self.build_temp, '-j4']
+        cmd = ['cmake', '--build', self.build_temp, '-j1']
         build_args = os.getenv('CMAKE_BUILD_ARGS')
         if build_args:
             cmd.extend(build_args.split(' '))
```

**Comment by wxj6000** [comment]
We have published the binary wheels. One can install gpu4pyscf via ```pip3 install gpu4pyscf-cuda11x```. I will close this issue.
