### ISSUE TITLE
Wrong results with pypi package on H100

### ISSUE THREAD

**Issue by wxj6000** [pyscf/gpu4pyscf#116]
If one install gpu4pyscf-cuda12x on a machine with H100, the DFT results are probably wrong. One needs to manually compile the package for sm90 architecture.

**Comment by sunqm** [comment]
Relies on the pypi tickets for package size limit:
https://github.com/pypi/support/issues/3675
https://github.com/pypi/support/issues/3676
https://github.com/pypi/support/issues/3677
https://github.com/pypi/support/issues/3678

**Comment by wxj6000** [comment]
resolved in https://github.com/pyscf/gpu4pyscf/pull/120
