### ISSUE TITLE
Hamiltonian computation does not use GPU

### ISSUE THREAD

**Issue by Obs01ete** [pyscf/gpu4pyscf#12]
I run the GPU-patched version of pyscf to compute the hamiltonian.
```python
import pyscf
from gpu4pyscf import patch_pyscf

from pyscf import gto, scf

def ...
    mol = gto.Mole()
    mol.atom = [(Z, pos) for Z, pos in zip(atomic_numbers, positions)]
    mol.basis = 'def2-tzvp'
    # number of electrons
    num_electrons = mol.nelectron

    if num_electrons % 2 != 0:
        mol.spin = 1
    else:
        mol.spin = 0

    mf = scf.RHF(mol)

    # Obtain the Hamiltonian matrix
    hcore = mf.get_hcore()

```
This code does not load my V100 unlike the example in README.md. What do I do to speed up this code with GPU?

**Comment by wxj6000** [comment]
Certain modules of GPU4PySCF are still running on CPU, such as mf.get_hcore(), since it is not very expensive.
More modules are moved into GPU in the recent release. The current release is gpu4pyscf-0.5. Please notice that the patch-mechanism may not be fully supported. You can explicitly import the module instead.
Here is the example. https://github.com/pyscf/gpu4pyscf/blob/master/examples/01-h2o_dftd3.py

**Comment by Obs01ete** [comment]
@wxj6000 Thank you for clarifying the state of the library. I'd be glad to see get_hcore() sped up in the future release of GPU4PySCF. For bigger molecules or crystal cells get_hcore runtime can go up to 10s of seconds. If course it is way faster than the DFT compute but it would be great to make use of my GPU.

**Comment by wxj6000** [comment]
Thank you for the feedback. I will add this to the future development.

**Comment by Obs01ete** [comment]
Sweet, sweet, that HF iterations now run on GPU nicely. Here is my benchmarking:
```
CPU 48 cores: 40 s/molecule
GPU V100: 15 s/molecule
GPU A100: 15 s/molecule
```

**Comment by wxj6000** [comment]
@Obs01ete Glad to hear that! Do A100 and V100 have the similar performance in your benchmark?

**Comment by Obs01ete** [comment]
> @Obs01ete Glad to hear that! Do A100 and V100 have the similar performance in your benchmark?
Yes. I am not sure why, though.
