### ISSUE TITLE
Compilation problem with CUDA

### ISSUE THREAD

**Issue by baopengbp** [pyscf/gpu4pyscf#23]
Hi,
I tried to compile in two nodes. 
One is the main node without gpu, but it has internet. I install CUDA11.8 without driver. 
The other is the gpu node with V100, but it has not internet. The CUDA11.8 and driver are installed.
The compilation problems are the same in both nodes.

I try to compile build.sh first. The result is:
CUDA_HOME=
'nvalid command name 'bdist_wheel
==============
Then I do     python setup.py bdist_wheel     (in build.sh) with cmake-3.22  several days before, the result is:

running bdist_wheel
running build
running build_ext
Configuring extensions
cmake -S/home/baop/research/gpu4pyscf/gpu4pyscf/lib -Bbuild/temp.linux-x86_64-3.7/gpu4pyscf -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.8/bin/nvcc
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/local/cuda-11.8/bin/nvcc
CMake Error in /home/baop/research/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeTmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_676f6".

CMake Error in /home/baop/research/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeTmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_676f6".

CMake Error at /usr/local/cmake/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:43 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
See also "/home/baop/research/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeOutput.log".
See also "/home/baop/research/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1
====================
Yesterday, using the new gpu4pyscf version, the result is：

running bdist_wheel
running build
running build_ext
Configuring extensions
cmake -S/home/baop/research/temp/g4p1/gpu4pyscf/gpu4pyscf/lib -Bbuild/temp.linux-x86_64-3.7/gpu4pyscf
-- The C compiler identification is GNU 4.8.5
-- The CUDA compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - failed
-- Check for working CUDA compiler: /usr/local/cuda-11.8/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.8/bin/nvcc - broken
CMake Error at /usr/local/cmake/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:56 (message):
  The CUDA compiler

    "/usr/local/cuda-11.8/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/baop/research/temp/g4p1/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_1a070/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_1a070.dir/build.make CMakeFiles/cmTC_1a070.dir/build
    gmake[1]: Entering directory `/home/baop/research/temp/g4p1/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_1a070.dir/main.cu.o
    /usr/local/cuda-11.8/bin/nvcc      -c /home/baop/research/temp/g4p1/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_1a070.dir/main.cu.o
    Linking CUDA executable cmTC_1a070
    /usr/local/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1a070.dir/link.txt --verbose=1
    "" CMakeFiles/cmTC_1a070.dir/main.cu.o -o cmTC_1a070 
    Error running link command: No such file or directory
    gmake[1]: *** [cmTC_1a070] Error 2
    gmake[1]: Leaving directory `/home/baop/research/temp/g4p1/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_1a070/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
See also "/home/baop/research/temp/g4p1/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeOutput.log".
See also "/home/baop/research/temp/g4p1/gpu4pyscf/build/temp.linux-x86_64-3.7/gpu4pyscf/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1
=====================================

**Comment by wxj6000** [comment]
Hi,
You should be able to compile the package without a GPU. You will need a GPU if the you install cutensor with `python -m cupyx.tools.install_library --cuda 11.x --library cutensor`

It seems your `CUDA_HOME` is not set up. Can you `export CUDA_HOME=/usr/local/cuda`?

Recently, we uploaded a dockerfile for compiling the package. It should be easier from there.
https://github.com/pyscf/gpu4pyscf/blob/master/dockerfiles/compile/Dockerfile

**Comment by baopengbp** [comment]
After export CUDA_HOME=/usr/local/cuda, the problem is still the same.

**Comment by wxj6000** [comment]
It seems that there is still some issue with your cuda environment. nvcc itself cannot compile a simple test problem. Unfortunately, cuda environment is very complicated. I recommend you use the dockerfile to create an environment.

**Comment by sunqm** [comment]
Install with setup.py may mix other irrelevant information. Can you try the direct compilation and post the output?
```
cd gpu4pyscf/lib
mkdir build
cd build
cmake ..
make
```

**Comment by baopengbp** [comment]
After direct compilation the latest version
cd gpu4pyscf/lib
mkdir build
cd build
cmake ..

The output is:

-- The C compiler identification is GNU 4.8.5
-- The CUDA compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CUDA compiler ABI info
CMake Error in /home/baop/research/gitdld/gpu4pyscf20231008/gpu4pyscf/lib/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_1b139".


CMake Error in /home/baop/research/gitdld/gpu4pyscf20231008/gpu4pyscf/lib/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_1b139".


CMake Error at /usr/local/cmake/share/cmake-3.22/Modules/CMakeDetermineCompilerABI.cmake:49 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/local/cmake/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:19 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:20 (project)


-- Configuring incomplete, errors occurred!
See also "/home/baop/research/gitdld/gpu4pyscf20231008/gpu4pyscf/lib/build/CMakeFiles/CMakeOutput.log".
See also "/home/baop/research/gitdld/gpu4pyscf20231008/gpu4pyscf/lib/build/CMakeFiles/CMakeError.log".


> Install with setup.py may mix other irrelevant information. Can you try the direct compilation and post the output?
> 
> ```
> cd gpu4pyscf/lib
> mkdir build
> cd build
> cmake ..
> make
> ```

**Comment by baopengbp** [comment]
> It seems that cmake cannot find your cuda compiler. Can you run the following script or add them into your ~/.bashrc (don't forget source ~/.bashrc)? You may want to change the path based on your setup.
> 
> ```
> export PATH=/usr/local/cuda-11.8/bin:$PATH
> export CUDA_HOME="/usr/local/cuda-11.8" 
> export CUTENSOR_ROOT="/usr/local/cuda-11.8"
> export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${CUDA_HOME}/lib:${LD_LIBRARY_PATH}"
> ```
> 
> You will need to make sure the CUDA env is ready first. I usually use 'nvcc --version' to test.

I use this env before:
export PATH=$PATH:/usr/local/cuda-11.8/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.8/lib64

and the nvcc --version is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

I try your env, but still get the same problem. I also try python3.7 and 3.9, there are no change.

**Comment by baopengbp** [comment]
[CMakeOutput.log](https://github.com/pyscf/gpu4pyscf/files/12889189/CMakeOutput.log)
[CMakeError.log](https://github.com/pyscf/gpu4pyscf/files/12889190/CMakeError.log)

Here are the cmake output

**Comment by baopengbp** [comment]
There are 4 V100 in the node

**Comment by baopengbp** [comment]
The error message is coming when project (gpu4pyscf C CUDA) in the beginning of CMakeLists.txt run.

**Comment by baopengbp** [comment]
I try cmake3.18, cuda10.1, TITAN V in an old node, the cmake  .. works. 
But I still want to use V100 because TITAN V maybe not stabilized and has small memory.

**Comment by baopengbp** [comment]
If pip install gpu4pyscf is OK, I will be very appreciate.

**Comment by baopengbp** [comment]
If pip install gpu4pyscf is OK, I will be very appreciate.

**Comment by sunqm** [comment]
pip wheel is available now

**Comment by baopengbp** [comment]
It works. Thanks.
It cannot be installed with python3.7 because cupy ask python3.8. I install gpu4pyscf with python3.9.
"python -m cupyx.tools.install_library --cuda 11.x --library cutensor" needs internet to download library.
I add DNS setting to make gpu node on internet.

> pip wheel is available now
