### ISSUE TITLE
[Question] Reference for the PBC QM/MM implementation

### ISSUE THREAD

**Issue by YuzheZhang98** [pyscf/gpu4pyscf#232]
In the original PySCF, the QM/MM module supports only non-periodic boundary conditions (non-PBC). However, in GPU4PySCF, it seems that only periodic boundary condition (PBC) QM/MM is implemented. Is there any reference paper or documentation available for the PBC QM/MM implementation in GPU4PySCF? Additionally, is it feasible to convert the QM/MM class between  PySCF and GPU4PySCF in a convenient way?

**Comment by wxj6000** [comment]
Here is the reference for PBC QM/MM https://arxiv.org/abs/2408.03273
@MoleOrbitalHybridAnalyst Do you have the plan to keep the consistency between GPU4PySCF and PySCF, in terms of QM/MM?

**Comment by MoleOrbitalHybridAnalyst** [comment]
Hello, you can find a CPU version of PBC QM/MM here [https://github.com/MoleOrbitalHybridAnalyst/pyscf/tree/qmmm](url)
