### ISSUE TITLE
Calculate the intermolecular interaction 

### ISSUE THREAD

**Issue by junminchen** [pyscf/gpu4pyscf#238]
#95 
from upper link, is there any example to calculate the intermolecular interaction? 
like the paper mentioned in "3.1.2 Dimer Interaction Energies"

or the psi4 input with bsse correction:

<img width="606" alt="image" src="https://github.com/user-attachments/assets/a8c6a5a2-b006-4694-b63d-229d11dea0ae">

**Comment by wxj6000** [comment]
PySCF does not provide a function for CP directly. An example of calculating CP corrected interaction energy is added in  https://github.com/pyscf/gpu4pyscf/pull/243

**Comment by junminchen** [comment]
Thank you!
