### ISSUE TITLE
Using CUDA 11 in the installation some of the problems encountered, part has been solved.

### ISSUE THREAD

**Issue by ChuixiongWu** [pyscf/gpu4pyscf#3]
Dear all,

My workstation uses nvidia rtx 3090 graphics card. So it has to use cuda11.
In python 3.7 or higher, cupy can be installed correctly, but setuptools faces a series of bugs at runtime.
1. Nonetype cannot iterate, because when setuptools calls utilities, it will use the list(None) operation, and an error will be reported here. However, this problem can be solved by a simple modification.
2. After installing cupy, the compiler will repeatedly encounter
```
Error: function "atomicAdd(double *, double)" is defined
```
I can't solve this problem.

I guess it might be because the version of cupy and cuda is too high. So I tried again with Python 3.6. Python 3.6 builds successfully, but the system still looks for cupy 11.0.0 by default when installing, even though I have cupy-cuda111 installed. cupy 11.0.0 cannot be installed on Python 3.6 because it requires numpy >= 1.20, and Python 3.6 only supports up to numpy 1.19.

So I don't think the current gpu4pyscf can run on cuda 11 yet. Because the version of cuda is too high and loses some features.

Also, on the current cupy installation requirements it says that python 3.7.0 or higher is required. So is it possible that the compile staff is using an older version of cupy?

Best,
CX.

**Comment by TaihuLight** [comment]
@ChuixiongWu How to fix the first bug? 
BTW, do you sucessfully install gpu4pyscf?

**Comment by TaihuLight** [comment]
@ChuixiongWu  I have successfully build and install gpu4pyscf with cuda 11.6. Please check the change in the pull requests.

**Comment by ChuixiongWu** [comment]
@TaihuLight Glad to learn about this.
I received your email yesterday about the first question, but I didn't check my email yesterday and I'm sorry about that.
I will test this change in PR soon and if there is no problem, I will close this issue
