### ISSUE TITLE
GPU hardware requirements

### ISSUE THREAD

**Issue by sef43** [pyscf/gpu4pyscf#65]
Hello can you specify what GPUs this will work on?
I get a `CUDA Error of gen grids: no kernel image is available for execution on the device` when running on a 1080 but with everything the same it works on a RTX3090

**Comment by wxj6000** [comment]
The package was compiled for Volta cards and later. Old cards (Pascal and before) are not supported. Adding the support for Pascal cards or specifying is a good suggestion.

**Comment by sunqm** [comment]
The pip wheel does not support older cards. You can compile the library for your card locally, with the compiling option `-DCUDA_ARCHITECTURES=60` . See 
https://github.com/pyscf/gpu4pyscf/blob/master/gpu4pyscf/lib/CMakeLists.txt#L27 . This will add the binary code for old cuda architecture.
