### ISSUE TITLE
compatibility issue in dftd3 build

### ISSUE THREAD

**Issue by sunqm** [pyscf/gpu4pyscf#81]
The dftd3 and dftd4 build script introduced in PR #79 builds the Python version specific binaries. However, the gpu4pyscf build system releases `py3-none` type wheels. The new wheel will have the compatibility issue. This issue needs to be fixed before 1.0 release.

I think it's better to put the gpu4pyscf-dftd3 and gpu4pyscf-dftd4 modules into a separate wheel.

**Comment by wxj6000** [comment]
It still has some other issues too. I am working on it. It should be resolved before next release.

**Comment by wxj6000** [comment]
The compilations of DFTD3 and DFTD4 (w/o openmp) are integrated into gpu4pyscf. The shared libraries will be released along with gpu4pyscf wheel. A thin wrapper is created for dftd3 and dftd4 separately.
