### ISSUE TITLE
Benchmark numbers

### ISSUE THREAD

**Issue by alexm-gc** [pyscf/gpu4pyscf#9]
Thanks for this amazing work!

Do you have benchmark numbers for simple things like 10 H20 in 6-31G or STO-G and B3LYP, comparing the running time of CPU and GPU implementation?

If not, is there any reason for why? Would it take a lot of work to produce the benchmarks?

**Comment by alexm-gc** [comment]
It looks like a 3x speed-up from  `Intel(R) Xeon(R) CPU @ 2.00GHz` to `Tesla T4`. 

**Question 0.** Do you get different numbers? 

Example: 10 H2O molecules in STO-3G with RKS/B3LYP

```  
  gpu		  cpu
6.974899	19.121617	
6.958666	22.960514	
6.905839	20.869292	
6.878995	18.451716	
7.138914	18.788693
```

Example: Benzene (C6H6) in 6-31G** with RKS/B3LYP

```
  gpu		  cpu
5.718811	10.618403	
5.807300	10.500370	
5.857789	10.442052	
5.990742	10.871001	
5.748997	10.544211
```

**Comment by wxj6000** [comment]
We haven't published any benchmark yet. The performance is improving in new releases. The performance with a small basis set is usually better than a large basis set on GPU, as you have shown. 3x speedup with Tesla T4 is not bad.

**Comment by wxj6000** [comment]
Benchmarking data is added, and will be updated.
