### ISSUE TITLE
DFT calculation crashes when using mol.cart=True

### ISSUE THREAD

**Issue by manassharma07** [pyscf/gpu4pyscf#99]
I tried running a density-fitting DFT calculation on a GPU with 

`mol.cart = True`

and it crashes. 

I assume that in the nascent stages, the Cartesian AOs may not have been a priority. But I would appreciate if this feature could be added in the near future if it is not so much work.

**Comment by wxj6000** [comment]
Thank you for the feedback. The cartesian AOs are supported in some modules. But it was not fully tested yet. It will be added in the next version.
